import { ShowcaseItemType } from "@site/src/types";

export const items: ShowcaseItemType[] = [
  {
    header: "Image One",
    description: "This is a description of the item",
    // href: "https://ionicframework.com/docs/icons/guide-installation-icon-hover.svg",
    href: "https://images.unsplash.com/photo-1506624183912-c602f4a21ca7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
    type: "image",
    icon: "/svg/image.svg",
    tags: ["image", "ionic"],
  },
  {
    header: "Link One",
    description: "This is a description of the item",
    href: "https://medium.com/r_joydip",
    type: "gist",
    icon: "/svg/link.svg",
    size: "md",
    tags: ["link", "medium"],
  },
  {
    header: "Image Two",
    description: "This is a description of the item",
    href: "https://images.unsplash.com/photo-1506624183912-c602f4a21ca7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
    icon: "/svg/image.svg",
    type: "image",
    tags: ["image", "unsplash"],
  },
  {
    header: "Video One",
    href: "https://youtu.be/aqz-KE-bpKQ",
    icon: "/svg/video.svg",
    type: "video",
    tags: ["video", "youtube"],
  },
  {
    header: "PDF One",
    description: "This is a description of the item",
    href: "http://africau.edu/images/default/sample.pdf",
    icon: "/svg/pdf.svg",
    type: "pdf",
    size: "md",
    tags: ["pdf"],
  },
  {
    header: "Link Two",
    description: "This is a description of the item",
    href: "https://medium.com/r_joydip",
    type: "gist",
    icon: "/svg/link.svg",
    size: "md",
    tags: ["link"],
  },
  {
    header: "Markdown One",
    description: "This is a description of the item",
    href: "https://raw.githubusercontent.com/rjoydip/webdev-learning/main/README.md",
    icon: "/svg/markdown.svg",
    type: "markdown",
    size: "lg",
    tags: [],
  },
  {
    header: "Image Three",
    description: "This is a description of the item",
    icon: "/svg/image.svg",
    type: "image",
    tags: ["image", "unsplash"],
  },
  {
    header: "Markdown Two",
    description: "This is a description of the item",
    href: "https://raw.githubusercontent.com/rjoydip/webdev-learning/main/README.md",
    icon: "/svg/markdown.svg",
    type: "markdown",
    size: "md",
    tags: ["markdown"],
  },
  {
    header: "Image Four",
    description: "This is a description of the item",
    href: "https://images.unsplash.com/photo-1506624183912-c602f4a21ca7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
    icon: "/svg/image.svg",
    type: "image",
    tags: ["image"],
  },
];
